version = 0.1
[dev.deploy.parameters]
stack_name = "serverless-shopping-cart"
resolve_s3 = true
s3_prefix = "serverless-shopping-cart"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
